CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login_id VARCHAR(255) NOT NULL COMMENT 'ログイン時に使用するユーザーID',
    password VARCHAR(255) NOT NULL COMMENT 'パスワード',
    name VARCHAR(255) NOT NULL COMMENT 'ユーザー名',
    avatar VARCHAR(255) NOT NULL COMMENT 'アバター画像のURL',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日'
);
