CREATE TABLE csrf_tokens (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    session_id VARCHAR(255) NOT NULL COMMENT 'セッションID',
    value VARCHAR(255) NOT NULL COMMENT 'トークンの値',
    expired_at DATETIME NOT NULL COMMENT '有効期限',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日',
    CONSTRAINT FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE ON UPDATE CASCADE
);
